### ISSUE TITLE
Update GitHub Actions versions in workflows

### ISSUE THREAD

**Issue by briantist** [ansible-collections/collection_template#41]
Many GitHub Actions from GitHub and even third parties have had major version bumps recently, looking to replace Node 12 (EoL this month) with a newer version.

This includes checkout, setup-python, and codecov which have all bumped to v3, github-script is up to v6, for anyone else using them, the peter-evans/find-comment and peter-evans/create-or-update-comment are up to v2.

We should go through and update. Opening an issue in case I can't get to a PR today.

Should we announce in news for maintainers?

Also consider dependabot for this in the future (separate discussion): https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

Example PRs:
- https://github.com/ansible-community/github-docs-build/pull/32
- https://github.com/ansible-collections/community.hashi_vault/pull/243
- https://github.com/lowlydba/lowlydba.sqlserver/pull/59

**Comment by felixfontein** [comment]
#43 fixes the workflows in this repo. (I also fixed the workflows in the repos I'm working with.)
