### ISSUE TITLE
devel branch now requires python >= 3.9

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ansible-collections/collection_template#46]
##### SUMMARY

See title

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

Clone/fork this repository and run the included github workflows.

##### EXPECTED RESULTS

Green checkmarks

##### ACTUAL RESULTS

An error similar to this one:

https://github.com/mgit-at/ansible-collection-roles/runs/7622603379

Apparently the `ubuntu-latest` runner in gh-workflows isn't THAT "latest", as Ubuntu 22.04 runs Python 3.10. The runner I got ran 20.04 instead. Probably needs to be `ubuntu-22.04` instead: https://github.com/actions/virtual-environments

**Comment by MarkusTeufelberger** [comment]
Hm, seems I forked my repo a bit too early, the current one here already has `python-version: '3.10'` set in the workflows so new ones should be fine for now.

**Comment by felixfontein** [comment]
Also with #29 and https://github.com/ansible-community/ansible-test-gh-action/pull/19 such updates should no longer be necessary :)

**Comment by webknjaz** [comment]
> Hm, seems I forked my repo a bit too early

You could always do `git merge --allow-unrelated-histories https://github.com/ansible-collections/collection_template.git`

**Comment by MarkusTeufelberger** [comment]
Well, the pipeline files contains sections that need to be modified downstream and others that should be kept 1:1 the same as in this repository, so this means resolving a few merge conflicts every now and then I guess... :thinking:

Nah, too much hassle for now, maybe in the future there's a way to better work with "template repositories" like this one. I'd rather not invent yet another way of doing things just for a single small repository and if it is something that all/most collections should use this needs more eyes and brains than just mine. :-)

**Comment by webknjaz** [comment]
> so this means resolving a few merge conflicts every now and then I guess... thinking

Yes and no. If you use a proper `git merge` (not `--squash` or "rebase"), Git will know where and how the history got connected, and it'll remember that some things aren't "integrated" into your repo. Of course, if it's small, choosing not to care is a perfectly valid option. Just saying that it's less bad with Git than it might seem...

For the future reference, I'd like to share this repository https://github.com/jaraco/skeleton — it's an interesting approach that my co-maintainer on some projects and the maintainer of setuptools uses for structuring projects on scale. In case you'll need such an approach in the future :)
