### ISSUE TITLE
Need to update ansible versions

### ISSUE THREAD

**Issue by samccann** [ansible-collections/collection_template#84]
##### SUMMARY

Not sure if this is an issue so this may just be me not understanding things.

1 - [meta/runtime.yml](https://github.com/ansible-collections/collection_template/blob/main/meta/runtime.yml#L2) still has ansible-core 2.11 as the base, but[ CI here](https://github.com/ansible-collections/collection_template/blob/main/.github/workflows/ansible-test.yml#L79) starts at 2.15. Should the runtime be updated to 2.15 to match what is actually tested?
2. Since CI is starting at 2.15, can we simplify the[ runs-on](https://github.com/ansible-collections/collection_template/blob/main/.github/workflows/ansible-test.yml#L79) to just ubuntu-latest? 

Happy to open PRs if I'm correct here...

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by felixfontein** [comment]
I think both changes are fine.

**Comment by samccann** [comment]
Cool I'll open a PR for both, thanks!
